export default {
  NODE_SIZE: 64,
  NODE_FILL: '#c6e5ff',
  NODE_STROKE: '#8ecafd',
  NODE_STROKE_WIDTH: 2,
  NODE_ICON_COLOR: '#8ecafd',
  NODE_TEXT_COLOR: '#595959',

  NODE_FILL_HOVER: '#e7f3fc',
  NODE_ICON_COLOR_HOVER: '#8ecafd',

  NODE_FILL_SELECTED: '#4794d4',
  NODE_ICON_COLOR_SELECTED: '#eef5fb',

  LINK_STROKE_WIDTH: 2,
  LINK_STROKE: '#a3b1bf',
  LINK_TEXT_COLOR: '#a3b1bf',

  LINK_STROKE_HOVER: '#788694',
  LINK_TEXT_COLOR_HOVER: '#788694',

  LINK_STROKE_SELECTED: '#4d5761',
  LINK_TEXT_COLOR_SELECTED: '#4d5761',

  TOOLTIP_FILL: 'rgba(0,0,0,0.7)',
  TOOLTIP_TEXT_COLOR: '#fff'
}


export const category1 = {
  NODE_SIZE: 64,
  NODE_FILL: '#f8c7c5',
  NODE_STROKE: '#9f504d',
  NODE_STROKE_WIDTH: 2,
  NODE_ICON_COLOR: '#9f504d',
  NODE_TEXT_COLOR: '#595959',

  NODE_FILL_HOVER: '#fbe8e7',
  NODE_ICON_COLOR_HOVER: '#9f504d',

  NODE_FILL_SELECTED: '#9f504d',
  NODE_ICON_COLOR_SELECTED: '#fff',

  LINK_STROKE_WIDTH: 2,
  LINK_STROKE: '#a3b1bf',
  LINK_TEXT_COLOR: '#a3b1bf',

  LINK_STROKE_HOVER: '#788694',
  LINK_TEXT_COLOR_HOVER: '#788694',

  LINK_STROKE_SELECTED: '#4d5761',
  LINK_TEXT_COLOR_SELECTED: '#4d5761',

  TOOLTIP_FILL: 'rgba(0,0,0,0.7)',
  TOOLTIP_TEXT_COLOR: '#fff'
}

export const category2 = {}

